
#ifndef GUARD_CONSTANTS_BATTLE_PARTNERS_H
#define GUARD_CONSTANTS_BATTLE_PARTNERS_H

#define PARTNER_NONE                0
#define PARTNER_STEVEN              1
#define PARTNER_KYLE_WOODS          2
#define PARTNER_BREN_WOODS          3
#define PARTNER_SPENCER_WOODS       4
#define PARTNER_SPENCER_MUSEUM      5
#define PARTNER_BREN_MUSEUM         6
#define PARTNER_KYLE_MUSEUM         7
#define PARTNER_WALLY_ROUTE_114     8

#endif  // GUARD_CONSTANTS_BATTLE_PARTNERS_H
